/**
 * Curated CIE-10 (ICD-10, Spanish PAHO edition) subset for school nursing.
 * The API also accepts any code typed manually and the admin can import the
 * full official catalog (CSV) with `npm run icd:import -w @sgee/api`.
 */
export const ICD10_SCHOOL: [code: string, description: string][] = [
  ['A09', 'Diarrea y gastroenteritis de presunto origen infeccioso'],
  ['A37.9', 'Tos ferina, no especificada'],
  ['B01.9', 'Varicela sin complicaciones'],
  ['B05.9', 'Sarampión sin complicaciones'],
  ['B08.4', 'Estomatitis vesicular enteroviral con exantema (mano-pie-boca)'],
  ['B26.9', 'Parotiditis sin complicación'],
  ['B34.9', 'Infección viral, no especificada'],
  ['B35.0', 'Tiña de la barba y del cuero cabelludo'],
  ['B85.0', 'Pediculosis debida a Pediculus humanus capitis'],
  ['B86', 'Escabiosis'],
  ['D66', 'Deficiencia hereditaria del factor VIII'],
  ['E10.9', 'Diabetes mellitus insulinodependiente, sin mención de complicación'],
  ['E16.2', 'Hipoglucemia, no especificada'],
  ['E66.9', 'Obesidad, no especificada'],
  ['E86', 'Depleción del volumen'],
  ['F32.9', 'Episodio depresivo, no especificado'],
  ['F41.0', 'Trastorno de pánico'],
  ['F41.9', 'Trastorno de ansiedad, no especificado'],
  ['F43.0', 'Reacción al estrés agudo'],
  ['F84.0', 'Autismo en la niñez'],
  ['F90.0', 'Perturbación de la actividad y de la atención'],
  ['G40.9', 'Epilepsia, tipo no especificado'],
  ['G43.9', 'Migraña, no especificada'],
  ['G44.2', 'Cefalea debida a tensión'],
  ['H10.9', 'Conjuntivitis, no especificada'],
  ['H52.7', 'Trastorno de la refracción, no especificado'],
  ['H53.9', 'Alteración visual, no especificada'],
  ['H57.1', 'Dolor ocular'],
  ['H66.9', 'Otitis media, no especificada'],
  ['H91.9', 'Hipoacusia, no especificada'],
  ['H92.0', 'Otalgia'],
  ['I49.9', 'Arritmia cardiaca, no especificada'],
  ['J00', 'Rinofaringitis aguda (resfriado común)'],
  ['J02.9', 'Faringitis aguda, no especificada'],
  ['J03.9', 'Amigdalitis aguda, no especificada'],
  ['J06.9', 'Infección aguda de las vías respiratorias superiores, no especificada'],
  ['J11.1', 'Influenza con otras manifestaciones respiratorias, virus no identificado'],
  ['J30.4', 'Rinitis alérgica, no especificada'],
  ['J45.9', 'Asma, no especificada'],
  ['J46', 'Estado asmático'],
  ['K02.9', 'Caries dental, no especificada'],
  ['K08.8', 'Otras afecciones especificadas de los dientes y de sus estructuras de sostén'],
  ['K12.0', 'Estomatitis aftosa recurrente'],
  ['K30', 'Dispepsia'],
  ['K90.0', 'Enfermedad celíaca'],
  ['L01.0', 'Impétigo'],
  ['L02.9', 'Absceso cutáneo, furúnculo y ántrax, de sitio no especificado'],
  ['L20.9', 'Dermatitis atópica, no especificada'],
  ['L23.9', 'Dermatitis alérgica de contacto, de causa no especificada'],
  ['L30.9', 'Dermatitis, no especificada'],
  ['L50.9', 'Urticaria, no especificada'],
  ['M25.5', 'Dolor en articulación'],
  ['M41.9', 'Escoliosis, no especificada'],
  ['M54.5', 'Lumbago no especificado'],
  ['M54.9', 'Dorsalgia, no especificada'],
  ['M79.1', 'Mialgia'],
  ['N94.6', 'Dismenorrea, no especificada'],
  ['Q24.9', 'Malformación congénita del corazón, no especificada'],
  ['R04.0', 'Epistaxis'],
  ['R05', 'Tos'],
  ['R06.0', 'Disnea'],
  ['R07.4', 'Dolor en el pecho, no especificado'],
  ['R10.1', 'Dolor abdominal localizado en parte superior'],
  ['R10.4', 'Otros dolores abdominales y los no especificados'],
  ['R11', 'Náusea y vómito'],
  ['R21', 'Salpullido y otras erupciones cutáneas no especificadas'],
  ['R25.2', 'Calambres y espasmos'],
  ['R42', 'Mareo y desvanecimiento'],
  ['R50.9', 'Fiebre, no especificada'],
  ['R51', 'Cefalea'],
  ['R53', 'Malestar y fatiga'],
  ['R55', 'Síncope y colapso'],
  ['R56.8', 'Otras convulsiones y las no especificadas'],
  ['R60.0', 'Edema localizado'],
  ['R73.9', 'Hiperglucemia, no especificada'],
  ['S00.3', 'Traumatismo superficial de la nariz'],
  ['S00.5', 'Traumatismo superficial del labio y de la cavidad bucal'],
  ['S00.9', 'Traumatismo superficial de la cabeza, parte no especificada'],
  ['S01.9', 'Herida de la cabeza, parte no especificada'],
  ['S02.2', 'Fractura de los huesos de la nariz'],
  ['S02.5', 'Fractura de los dientes'],
  ['S05.9', 'Traumatismo del ojo y de la órbita, no especificado'],
  ['S06.0', 'Concusión'],
  ['S09.9', 'Traumatismo de la cabeza, no especificado'],
  ['S20.2', 'Contusión del tórax'],
  ['S30.0', 'Contusión de la región lumbosacra y de la pelvis'],
  ['S40.0', 'Contusión del hombro y del brazo'],
  ['S50.0', 'Contusión del codo'],
  ['S60.9', 'Traumatismo superficial de la muñeca y de la mano, no especificado'],
  ['S63.5', 'Esguince y torcedura de la muñeca'],
  ['S70.0', 'Contusión de la cadera'],
  ['S80.0', 'Contusión de la rodilla'],
  ['S90.3', 'Contusión de otras partes y de las no especificadas del pie'],
  ['S93.4', 'Esguince y torcedura del tobillo'],
  ['T14.0', 'Traumatismo superficial de región no especificada del cuerpo'],
  ['T14.1', 'Herida de región no especificada del cuerpo'],
  ['T14.9', 'Traumatismo, no especificado'],
  ['T15.9', 'Cuerpo extraño en parte externa del ojo, sitio no especificado'],
  ['T17.9', 'Cuerpo extraño en el sistema respiratorio, parte no especificada'],
  ['T30.0', 'Quemadura de región del cuerpo no especificada, grado no especificado'],
  ['T63.0', 'Efecto tóxico del veneno de serpiente'],
  ['T63.4', 'Efecto tóxico del veneno de otros artrópodos'],
  ['T67.0', 'Golpe de calor e insolación'],
  ['T78.2', 'Choque anafiláctico, no especificado'],
  ['T78.3', 'Edema angioneurótico'],
  ['T78.4', 'Alergia no especificada'],
  ['U07.1', 'COVID-19, virus identificado'],
  ['Z00.1', 'Control de salud de rutina del niño'],
  ['Z01.0', 'Examen de ojos y de la visión'],
  ['Z01.1', 'Examen de oídos y de la audición'],
  ['Z71.9', 'Consulta, no especificada'],
];

export function searchIcd10(q: string, limit = 20) {
  const n = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();
  const query = n(q.trim());
  if (!query) return ICD10_SCHOOL.slice(0, limit).map(([code, description]) => ({ code, description }));
  return ICD10_SCHOOL.filter(([code, d]) => n(code).startsWith(query) || n(d).includes(query))
    .slice(0, limit)
    .map(([code, description]) => ({ code, description }));
}
